const ROLES = {
  CUSTOMER: 'CUSTOMER',
  SHOPKEEPER: 'SHOPKEEPER',
  DELIVERY: 'DELIVERY',
  ADMIN: 'ADMIN'
};

const ORDER_STATUS = {
  PLACED: 'PLACED',
  ACCEPTED: 'ACCEPTED',
  PROCESSING: 'PROCESSING',
  PACKING: 'PACKING',
  READY: 'READY',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  PICKED_UP: 'PICKED_UP',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED'
};

const GRAIN_SOURCES = {
  CUSTOMER: 'CUSTOMER', // Customer provides their own grain
  MILL: 'MILL',         // Mill provides grain
  VENDOR: 'VENDOR'      // Vendor supplied
};

const SERVICE_TYPES = {
  GRINDING: 'GRINDING',
  PACKING: 'PACKING',
  DELIVERY: 'DELIVERY',
  CLEANING: 'CLEANING'
};

const FULFILLMENT_TYPES = {
  DELIVERY: 'DELIVERY',
  PICKUP: 'PICKUP'
};

const DELIVERY_STATUS = {
  ASSIGNED: 'ASSIGNED',
  PICKED_UP_FROM_MILL: 'PICKED_UP_FROM_MILL',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  ARRIVED: 'ARRIVED',
  DELIVERED: 'DELIVERED'
};

module.exports = {
  ROLES,
  ORDER_STATUS,
  GRAIN_SOURCES,
  SERVICE_TYPES,
  FULFILLMENT_TYPES,
  DELIVERY_STATUS
};
