const ROLES = {
  CUSTOMER: 'CUSTOMER',
  SHOPKEEPER: 'SHOPKEEPER',
  DELIVERY: 'DELIVERY',
  ADMIN: 'ADMIN'
};

const ORDER_STATUS = {
  // Master Standard Status Flow
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  MILLING: 'MILLING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',

  // Failure / Terminal States
  CANCELLED: 'CANCELLED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  RETURNED: 'RETURNED',

  // Compatibility names for existing tests and models
  PLACED: 'PLACED',
  ACCEPTED: 'ACCEPTED',
  PROCESSING: 'PROCESSING',
  PACKING: 'PACKING',
  READY: 'READY',
  PICKED_UP: 'PICKED_UP',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED'
};

const GROUP_RUN_STATUS = {
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  AT_MILL: 'AT_MILL',
  IN_TRANSIT: 'IN_TRANSIT',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const GRAIN_SOURCES = {
  CUSTOMER: 'CUSTOMER', // Customer provides their own grain
  MILL: 'MILL',         // Mill provides grain
  VENDOR: 'VENDOR'      // Vendor supplied
};

const SERVICE_TYPES = {
  GRINDING: 'GRINDING',
  PACKING: 'PACKING',
  DELIVERY: 'DELIVERY',
  CLEANING: 'CLEANING'
};

const FULFILLMENT_TYPES = {
  DELIVERY: 'DELIVERY',
  PICKUP: 'PICKUP'
};

const DELIVERY_STATUS = {
  ASSIGNED: 'ASSIGNED',
  PICKED_UP_FROM_MILL: 'PICKED_UP_FROM_MILL',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  ARRIVED: 'ARRIVED',
  DELIVERED: 'DELIVERED'
};

module.exports = {
  ROLES,
  ORDER_STATUS,
  GROUP_RUN_STATUS,
  GRAIN_SOURCES,
  SERVICE_TYPES,
  FULFILLMENT_TYPES,
  DELIVERY_STATUS
};
